#Author: John Patrick Ryan Mandal
name: Manual PR Creation

on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "Source branch (e.g., main)"
        required: true
        default: "DEV"
      to_branch:
        description: "Target branch (e.g., dev)"
        required: true
        default: "PROD"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Create Pull Request
        run: |
          gh pr create --base ${{ github.event.inputs.to_branch }} --head ${{ github.event.inputs.from_branch }} --title "Automated Pull Request: ${{ github.event.inputs.from_branch }} → ${{ github.event.inputs.to_branch }} | $(git log -1 --pretty=format:%s)"  --body "This PR was created as part of an automated workflow. Please review the changes."
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
