name: Deploy Next.js (Client) to Vercel

on:
  workflow_dispatch:

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Link Project (if not already linked)
        run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: client

      - name: Deploy Client to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: client
